stages:
    - install
    - lint
    - build
    - deploy

default:
    image: node:18

install:
    stage: install
    script:
        - npm install
    artifacts:
        paths:
            - node_modules

lint:
    stage: lint
    dependencies:
        - install
    script:
        - npm run lint
        - npm run format --check
        - npm run stylelint

build:
    stage: build
    dependencies:
        - install
    script:
        - npm run build
    artifacts:
        paths:
            - 'build/'
